name: visora_ai
description: Visora - Ultimate AI Video Studio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  blur: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/loading.json
    - assets/lottie/done.json
    - assets/logo/visora_logo.png
    - assets/logo/visora_logo_splash.png
    - assets/logo/visora_logo_white.png
    - assets/logo/visora_logo_dark.png
    - assets/logo/visora_full_text.png
    - assets/logo/visora_brand_banner.png
