name: Build Signed Flutter APK (Cloud Only)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.2'

    - name: Flutter pub get
      run: flutter pub get

    - name: Decode keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > visora-key.keystore

    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=visora-key.keystore" >> android/key.properties

    - name: Accept Android licenses
      run: yes | flutter doctor --android-licenses

    - name: Build Signed Release APK
      run: flutter build apk --release --dart-define=BASE_URL=https://visora-ai-5nqs.onrender.com

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: visora-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
