name: Build Flutter Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses || true

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: visora-release-apk
          path: build/app/outputs/flutter-apk/*.apk
